apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Qwen3-14B-quantized
    serving.kserve.io/deploymentMode: RawDeployment
  name: qwen3-14b-quantized
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '24'
          memory: 64Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '12'
          memory: 32Gi
          nvidia.com/gpu: '1'
      runtime: qwen3-14b-quantized-w4a16
      storageUri: pvc://qwen3-14b-quantized-w4a16/qwen3-14b-quantized-w4a16
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
